apiVersion: v1
kind: Service
metadata:
  name: blue-svc
spec:
  type: NodePort
  ports:
    - port: 5000       # The port the service exposes inside the cluster
      targetPort: 5000 # The port your container/application is listening on
      protocol: TCP
  selector:
    app: blue          # Initial default routing (Jenkins will overwrite this dynamically)
